'use strict';

/**
 * Signed file download
 * --------------------
 * Routes that serve user-uploaded files (currently only resumes).
 * The URL is generated by `storage.signUrl(...)` and looks like:
 *
 *   /api/v1/files/<bucket>/<filename>?exp=<unix>&sig=<hmac>
 *
 * The signature is keyed to JWT_SECRET, so it can only be produced
 * server-side and tampering invalidates it. Expired or invalid
 * signatures return 403 without revealing whether the file exists.
 */

const express = require('express');
const path = require('node:path');

const storage = require('../services/storage.service');
const response = require('../utils/response.helper');

const router = express.Router();

router.get('/:bucket/:filename', (req, res) => {
  const { bucket, filename } = req.params;
  const { exp, sig, dl } = req.query;

  const storagePath = path.join(bucket, filename);
  // `dl` (when present) is part of the HMAC payload, so a tampered
  // attachment-name string fails verification.
  const ok = storage.verifySignedUrl(storagePath, exp, sig, dl || null);
  if (!ok) return response.forbidden(res, 'Signed URL invalid or expired');
  if (!storage.exists(storagePath)) return response.notFound(res, 'File not found');

  // When the caller signed the URL with an attachment name, force the
  // browser to download instead of inline-render and surface a
  // human-readable filename. Otherwise we keep the legacy inline
  // behaviour so existing callers (resume preview, etc.) still work.
  const disposition = dl
    ? `attachment; filename="${String(dl).replace(/"/g, '')}"`
    : 'inline';
  return res.sendFile(storage.absolutePath(storagePath), {
    headers: { 'Content-Disposition': disposition },
  });
});

module.exports = router;
